version: "3.3"
services:
  janus:
    image: qtum/janus:dev
    build:
      context: ../../
      dockerfile: ./Dockerfile
      cache_from:
        - golang:1.14-alpine
        - qtum/janus:dev
    ports:
      - "23889:23889"
    environment:
      - QTUM_RPC=http://qtum:testpasswd@qtum:3889
    volumes:
      - ../standalone/myaccounts.txt:$GOPATH/github.com/qtumproject/janus/myaccounts.txt
    depends_on:
      - qtum
    command: --bind 0.0.0.0 --accounts /go/src/github.com/qtumproject/janus/myaccounts.txt --dev
  qtum:
    ports:
      - "3889:3889"
    image: qtum/qtum-seeded
    build:
      context: ../../docker
      dockerfile: ./qtum-seeded.Dockerfile
      cache_from:
        - qtum/qtum-seeded
    container_name: qtum_seeded_testchain
    command: qtumd -regtest -rpcbind=0.0.0.0:3889 -rpcallowip=0.0.0.0/0 -logevents -rpcuser=qtum -rpcpassword=testpasswd -deprecatedrpc=accounts -printtoconsole
  openzeppelin:
    image: qtum/janus-openzeppelin
    build:
      context: .
      dockerfile: ./openzeppelin.Dockerfile
      cache_from:
        - qtum/janus-openzeppelin
    depends_on:
      - janus
    command: truffle test --network docker
